name: AwsCdkUpgrade
on:
  schedule:
    - cron: 0 6 * * *
  workflow_dispatch: {}
jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.17.0
      - run: AWS_CDK_LATEST_RELEASE=$(npx github-release-tagname --user aws --repo aws-cdk --number-only) npx projen@0.3.47
      - run: yarn install
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.AWSCDK_UPGRADE_GITHUB_TOKEN }}
          commit-message: "chore: upgrade awscdk"
          branch: auto/awscdk-upgrade
          title: "chore: upgrade awscdk"
          body: This PR upgrades AWS CDK to the latest version
